---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: israel@izroll.dev
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          azureDNS:
            clientID: <clientId>
            clientSecretSecretRef:
            # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
              name: azuredns-config
              key: client-secret
            subscriptionID: <sub>
            tenantID: <tenant>
            resourceGroupName: izroll-dev
            hostedZoneName: izroll.dev
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud 