globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - "--providers.kubernetesingress.allowexternalnameservices"
  - "--providers.kubernetescrd.allowexternalnameservices"
  - "--experimental.plugins.htransformation.modulename=github.com/tomMoulard/htransformation"
  - "--experimental.plugins.htransformation.version=v0.2.7"

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []
  additionalVolumes:
  - name: plugins
  
additionalVolumes:
- name: plugins
additionalVolumeMounts:
- name: plugins
  mountPath: /plugins-storage

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      
ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: <metallb-ip> # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []